<?php
/**
 * InfoBeans Sales Shipment Comment Extension
 *
 * @category   Infobeans
 * @package    Infobeans_OSComments
 * @version    2.0.0
 *
 * Release with version 2.0.0
 *
 * @author     InfoBeans Technologies Limited http://www.infobeans.com/
 * @copyright  Copyright (c) 2017 InfoBeans Technologies Limited
 */

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order    = $block->getOrder() ?>
<?php if ($_shipment && $_order): ?>
<?php 
// infobeans shipping comments
$osHelper = $this->helper('Infobeans\OSComments\Helper\Data');
if($osHelper->isModuleEnabled()){
    $showComments = $osHelper->showBlankShippingComment();
    if($showComments || $_order->getDeliveryComment()!=""){
?>
<div class="block block-order-details-view">
    <div class="block-title">
        <span><h3><?php echo __($osHelper->getShippingLabel()) ?> :- </h3>
        <?php 
            echo __($_order->getDeliveryComment());
            if($showComments && $_order->getDeliveryComment()==""){
                echo __("N/A");
            }
        ?></span>
    </div>
</div><br>
<?php 
    }
}
//infobeans shipping comments ends
?>
    <table class="email-items">
        <thead>
            <tr>
                <th class="item-info">
                    <?= /* @escapeNotVerified */  __('Items'); ?>
                </th>
                <th class="item-qty">
                    <?= /* @escapeNotVerified */  __('Qty'); ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_shipment->getAllItems() as $_item): ?>
            <?php
                if ($_item->getOrderItem()->getParentItem()) {
                    continue;
                }
            ?>
            <tbody>
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
