<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
<?php if ($block->isHomePage()):?>
    <strong class="logo">
<?php else: ?>
    <a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
<?php endif ?>
        
        <?php
			$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
		    $baseurl = $storeManager->getStore()->getBaseUrl();
		   
		    $customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory')->create();
		    if ($customerSession->isLoggedIn ()) {
			 $customerId = $customerSession->getCustomer()->getId();
	 

			    $model = $objectManager->create('\Magedelight\MembershipSubscription\Model\MembershipOrders')->getCollection();
	            $model->addFieldToFilter('customer_id', $customerId);
	            $model->addFieldToFilter('order_status', 'complete');
	            $model->addFieldToFilter('plan_expiry_status', 0);
	            $model->setOrder('membership_order_id', 'DESC');
	            $data = $model->getData();
	            if (count($data)>0) {
	            	
	            	if ($data[0]['plan_expiry_date'] !== "" || $data[0]['plan_expiry_date'] !== "0000-00-00 00:00:00") { ?>
	            		 <img src="<?php echo $baseurl;?>pub/media/wysiwyg/home/logo.png"
			             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
			             <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
			             <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
			        	/>
	            	<?php } else{ ?>
	            		<img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
			             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
			             <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
			             <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
			        	/>
	            <?php } ?>
	            	
	                
	            <?php } else { ?>
	                	<img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
				             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
				             <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
				             <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
				        	/>
	            <?php }
	        }else{ ?>
		 		<img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        	/>

		 <?php }
		?>

<?php if ($block->isHomePage()):?>
    </strong>
<?php else:?>
    </a>
<?php endif?>


<script type="text/javascript">
require([ 'jquery', 'jquery/ui'], function($){ 
	$(document).ready(function($) {
		/*$('select[name="custom_attributes[address_book]"]').change(function(){
			var addressval = jQuery(this).find(':selected').val();
			// alert(addressval);
		});*/
		/*if ($(window).width() < 768) {
			$('.customer-welcome div.customer-menu').css('display','none');
			$('.customer-welcome .customer-name').click(function(){
				setTimeout(function(){ 
				if($('.customer-welcome.active').length == 1){
					$('.customer-welcome div.customer-menu').css('display','block');
				}else{
					$('.customer-welcome div.customer-menu').css('display','none');
				}
				}, 500);	
			});
		}*/
	}); 
});
</script>
