<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $baseurl = $storeManager->getStore()->getBaseUrl();
    // $catId = 62;  //Parent Category ID
   
    $_helper = $this->helper('Magento\Catalog\Helper\Output');

    $storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORES;
    $catid = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('magemonkey_general/general/home_catid', $storeScope);
    // echo "<pre>";
    if($catid != '')
    {
	    $catarray = explode(",", $catid);
	    // print_r($catarray); exit();
		$j = 1;
		foreach ($catarray as $catid) 
		{
		$Category = $objectManager->create('Magento\Catalog\Model\Category')->load($catid);
	    $subCats = $Category->getChildrenCategories();
		 if (count($subCats) > 0 && $Category->getIsActive()): ?>
			<div class="category-section">
					<h2 class="cate-title mp-product-slider-title"><?php echo $Category->getName(); ?></h2>
					<div class="subcat-sec">
						<ul>
						<?php $i=1; foreach ($subCats as $subcats): ?>
							<?php 
							
							$category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcats->getId());
							// print_r($category->getData());
		                    $cattitle = $category->getName();
		                    $caturl = $baseurl.$subcats->getRequestPath();
		                    $parentcat = $category->getParentCategory();
		                    if($category->getIsActive() && $category->getHomeSubCategory()):
							?>
							<li>
							<div class="cat_thumb">
	                                <a href="<?php echo $caturl;?>" class="p_view">
	                                 
	                                    <?php if((strpos($category->getCategorythumb(), 'category') !== false)) { $imgurl = $category->getCategorythumb(); } else { $imgurl =  'pub/media/catalog/category/'.$category->getCategorythumb();} ?>
	                                    <img  class="lazy" src="<?php echo $baseurl.$imgurl; ?>" data-original="<?php echo $baseurl.$imgurl; ?>" alt=" <?php echo $cattitle ?>"/>
	                                </a>
	                                <a href="<?php echo $caturl;?>" class="home-cattitle">
	                                    <span><?php echo $cattitle ?></span>
	                                </a>
	                          </div>
							</li>
						<?php
						$i++;
						if($i > 4){
							break;
						}
						endif;
						
						endforeach; ?>
						</ul>
					</div>
					<span class="cat-url"><a href="<?php echo $Category->getUrl();?>">See the range</a></span>
			</div>
			
		<?php endif; 
			$j++;
			if($j > 4)
			{
				break;
			}
		}
	}
?>