<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $baseurl = $storeManager->getStore()->getBaseUrl();

    $helper = $objectManager->get('Apptha\Marketplace\Helper\Objectmanager');
	$customerSession = $helper->customerSession();
	$customerDatas = $customerSession->getCustomer ();
	if ($customerSession->isLoggedIn ()) {
	 $customerId = $customerSession->getId ();
	 $customerGroupId = $customerDatas->getGroupId ();
	 $sellerGroupData = $helper->customerSessionGroup($customerGroupId);
	 $sellerGroupId = $sellerGroupData->getId ();
	 $status = $helper->sellerStatus( $customerId); 
	 
	 	if($sellerGroupId == 4 && $status == 1){
	 ?>

	 <li class="sellerrequest-link">  
	   <a href="<?php echo $baseurl;?>seller-request-form"><?php echo __('Seller Request Form');?></a>
	</li>

	<?php }
		// print_r($sellerGroupId);
		// exit();
	 }
?>
