<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');

if($customerSession->isLoggedIn()) {
   $customerid = $customerSession->getCustomer()->getId();
    

$lastyear = date('Y-m-d', strtotime("-1 year"));
$orderCollection = $objectManager->create('\Magento\Sales\Model\ResourceModel\Order\Collection');
$orderCollection->addAttributeToFilter('customer_id',$customerid)
            ->addAttributeToFilter('status','complete')
            ->addAttributeToFilter('created_at', array('gteq'  => $lastyear))->load();

echo "<pre>";print_r($orderCollection->getData()); exit;
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $baseurl = $storeManager->getStore()->getBaseUrl();
    $catId = 49;  //Parent Category ID
    $subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
    $childcat = $subcategory->getChildrenCategories(); 
    // echo "<pre>";
    // print_r($childcat->getData());
    // exit;

if (count($childcat) > 0): ?>
    <div class="carousel-container custom-carousel">
        <h2 class="cate-title mp-product-slider-title"><?php echo  $subcategory->getName();?></h2>
        <div id="department-slider-carousel">
            <?php $iterator = 1; ?>
            <div id="department-category-list" class="owl-carousel owl-theme">
                <?php $i = 0;
                foreach ($childcat as $subcats): ?>
                    <?php
                    $category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcats->getId());
                    $cattitle = $category->getName();
                    $caturl = $baseurl.$subcats->getRequestPath();
                    $parentcat = $category->getParentCategory(); 
                    // echo "<pre>";
                    // print_r($parentcat->getId());
                    // exit;
                    if($parentcat->getId() == $catId){

                    ?>
                    <?php echo ($iterator++ == 1) ? '<div class="category-item category-slider">' : '</div><div class="category-item category-slider">' ?>
                        <div class="item-image">
                            <div class="cat_thumb">
                                <a href="<?php echo $caturl;?>" class="p_view">
                                    <img src="<?php echo $baseurl.'pub/media/catalog/category/'.$category->getCategorythumb();?>" alt=" <?php echo $cattitle ?>"/>
                                </a>
                                <a href="<?php echo $caturl;?>" class="home-cattitle">
                                    <span><?php echo $cattitle ?></span>
                                </a>
                            </div>
                        </div>
                    <?php echo ($iterator == count($childcat) + 1) ? '</div>' : '' ?>
                <?php
                $i++;
                }
                endforeach; ?>
            </div>
        </div>
        <?php //echo $block->getPagerHtml() ?>
    </div>

    <script>

        /*require(['jquery', 
            'mageplaza/core/owl.carousel'], function ($) {
            $('#valentine-category-list').owlCarousel({
                "autoWidth":0,
                "autoHeight":1,
                "loop":0,
                "nav":0,
                "dots":1,
                "lazyLoad":0,
                "autoplay":1,
                "autoplayTimeout":5000,
                "animateOut":"none",
                "items":1

            });
        });*/
        require([
                'jquery',
                'mageplaza/core/owl.carousel'
            ], function ($) {
                jQuery("#department-category-list").owlCarousel({
                    responsive:{
                        0:{
                            items:1
                        },
                        480:{
                            items:2
                        },
                        768:{
                            items:3
                        },
                        992:{
                            items:5
                        },
                        1200:{
                            items:6
                        }
                    },
                    autoWidth:0,
                    autoHeight:1,
                    autoplay:false,
                    loop:true,
                    nav : true,
                    dots: false,
                    autoplaySpeed : 5000,
                    navSpeed : 500,
                    dotsSpeed : 500,
                    autoplayHoverPause: true,
                    margin:30,
                });   
            }); 
                
    </script>
<?php endif; ?>
<?php } ?>
