<?php
/**
 * Webkul Software.
 *
 * PHP version 7.0+
 *
 * @category  Webkul
 * @package   Webkul_DeliveryBoy
 * @author    Webkul <support@webkul.com>
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html ASL Licence
 * @link      https://store.webkul.com/license.html
 */
?>
<div class="rating-box">
    <div class="rating" style="width:<?= $block->escapeHtmlAttr($block->getRatingSummary()*20) ?>%;"></div>
</div>