<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$productId = $_item->getProductId();
$objectManagerHere = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManagerHere->get('Magento\Catalog\Model\Product')->load($productId);
$productImage = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'category_page_list', array('height' => '135' , 'width'=> '135'))->getUrl();
 ?>
 
 
 <?php         
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $proid = $objectManager->get('Magento\Catalog\Model\Product')->getIdBySku($block->getSku($_item));
    $product = $objectManager->create('Magento\Catalog\Model\Product')->load($proid);
    if($product->getSellerId()){
        $customerObj = $objectManager->create('Magento\Customer\Model\Customer')->load($product->getSellerId());
        $sellername = ucfirst($customerObj->getFirstname())." ".ucfirst($customerObj->getLastname());
    }else{
        $sellername = "Shop.bs";
    }
?> 
 
 
 
<tr width="100%">
<td>
<table>
<tr>

	<td class="item-thumbnail">
        <img src="<?= $productImage ?>" alt="<?= __('Product Image');?>" style="vertical-align:top;" />
    </td>

    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= /* @escapeNotVerified */  __('SKU') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option): ?>
                    <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                    <dd>
                        <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
	
</tr>	
</table>	
</td>	
	
	
    <td class="item-qty"><?= /* @escapeNotVerified */  $_item->getQty() * 1 ?></td>
</tr>
