<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $baseurl = $storeManager->getStore()->getBaseUrl();
    // $catId = 49;  //Parent Category ID
    $storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORES;
    $title = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('magemonkey_general/general/department_title', $storeScope);
    $catId = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('magemonkey_general/general/department_catid', $storeScope);
    $subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
    $childcat = $subcategory->getChildrenCategories(); 
    

if (count($childcat) > 0): ?>
    <div class="carousel-container custom-carousel">
        <div id="department-category">
            <?php $iterator = 1; ?>
            <ol id="department-cust-category-list">
                <?php $i = 0;
                foreach ($childcat as $subcats): ?>
                    <?php
                    $category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcats->getId());
                    $cattitle = $category->getName();
                    $caturl = $baseurl.$subcats->getRequestPath();
                    $parentcat = $category->getParentCategory(); 
                    // echo "<pre>";
                    // print_r($parentcat->getId());
                    // exit;
                    if($parentcat->getId() == $catId){

                    ?>
                    <?php echo ($iterator++ == 1) ? '<li class="category-item category-slider">' : '</li><li class="category-item category-slider">' ?>
                        <div class="item-image">
                            <div class="cat_thumb">
                                <a href="<?php echo $caturl;?>" class="p_view">
                                         <?php if((strpos($category->getCategorythumb(), 'category') !== false)) { $imgurl = $category->getCategorythumb(); } else { $imgurl =  'pub/media/catalog/category/'.$category->getCategorythumb();} ?>
                                  
                                    
                                    <img src="<?php echo $baseurl.$imgurl; ?>" alt=" <?php echo $cattitle ?>"/>
                                </a>
                                <a href="<?php echo $caturl;?>" class="home-cattitle">
                                    <span><?php echo $cattitle ?></span>
                                </a>
                            </div>
                        </div>
                    <?php echo ($iterator == count($childcat) + 1) ? '</ol>' : '' ?>
                <?php
                $i++;
                }
                endforeach; ?>
            </ol>
        </div>
        <?php //echo $block->getPagerHtml() ?>
    </div>

    <script>

        /*require(['jquery', 
            'mageplaza/core/owl.carousel'], function ($) {
            $('#valentine-category-list').owlCarousel({
                "autoWidth":0,
                "autoHeight":1,
                "loop":0,
                "nav":0,
                "dots":1,
                "lazyLoad":0,
                "autoplay":1,
                "autoplayTimeout":5000,
                "animateOut":"none",
                "items":1

            });
        });*/
       /* require([
                'jquery',
                'mageplaza/core/owl.carousel'
            ], function ($) {
                jQuery("#department-category-list").owlCarousel({
                    responsive:{
                        0:{
                            items:2
                        },
                        480:{
                            items:2
                        },
                        768:{
                            items:3
                        },
                        992:{
                            items:5
                        },
                        1200:{
                            items:6
                        }
                    },
                    autoWidth:0,
                    autoHeight:1,
                    autoplay:false,
                    loop:true,
                    nav : true,
                    dots: false,
                    autoplaySpeed : 5000,
                    navSpeed : 500,
                    dotsSpeed : 500,
                    autoplayHoverPause: true,
                    margin:30,
                });   
            }); 
              */  
    </script> 
<?php endif; ?>
