<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $baseurl = $storeManager->getStore()->getBaseUrl();
    // $catId = 41;  //Parent Category ID
    $storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORES;
    $title = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('magemonkey_general/general/giftshop_title', $storeScope);
    $catId = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('magemonkey_general/general/giftshop_catid', $storeScope);

    $collection = $objectManager->get('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory')->create();
    $collection->addAttributeToSelect('*');
    $collection->addAttributeToFilter('is_featured',1);
    $collection->addAttributeToSort('entity_id', 'DESC');
    $collection->setPageSize(5);
    $collection->load();

    

// $blockObj= $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
    $blockObj = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');


if (count($collection) > 0): ?>
    <div class="carousel-container custom-carousel featured-carousel">
        <h2 class="cate-title mp-product-slider-title"><?php echo __('Featured New Item');?></h2>
        <div class="viewdetails"><a href="<?php echo $baseurl?>featured-item">See All</a></div>
        <div id="featured-slider-carousel">
            <?php $iterator = 1; ?>
            <div id="featured-list" class="owl-carousel owl-theme">
                <?php foreach ($collection as $items): ?>
                    <?php
                    $product = $objectManager->create('Magento\Catalog\Model\Product')->load($items->getId());
                    $name = $product->getName();
                    ?>
                    <?php echo ($iterator++ == 1) ? '<div class="category-item category-slider">' : '</div><div class="category-item category-slider ">' ?>
                        <div class="slider-product-item-info">
                            <div class="product-img">
                                <a href="<?php echo $blockObj->getProductUrl($product) ?>"
                               class="product photo slider-product-item-photo">
                                    <?php echo $blockObj->getImage($product, 'recently_viewed_products_grid_content_widget')->toHtml(); ?>
                                </a>
                            </div>
                                                        <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="<?php echo $blockObj->escapeHtml($product->getName()) ?>"
                                       href="<?php echo $blockObj->getProductUrl($product) ?>">
                                        <?php echo $blockObj->escapeHtml($product->getName()) ?>
                                    </a>
                                </strong>
                                <?php echo $blockObj->getProductPrice($product); ?>
                               <?php /* <div class="product actions slider-product-item-actions">
                                    <div class="actions-primary">
                                        <?php if ($product->isSaleable()): ?>
                                            <?php if ($product->getTypeInstance()->hasRequiredOptions($product)): ?>
                                                <button class="action tocart primary mageplaza-product-slider-button"
                                                        data-mage-init='{"redirectUrl": {"url": "<?php echo $blockObj->getAddToCartUrl($product) ?>"}}'
                                                        type="button" title="<?php echo __('Add to Cart') ?>">
                                                    <span><?php echo __('Add to Cart') ?></span>
                                                </button>
                                            <?php else: ?>
                                                <?php
                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                $postData = $postDataHelper->getPostData($blockObj->getAddToCartUrl($product), ['product' => $product->getEntityId()])
                                                ?>
                                                <button class="action tocart primary mageplaza-product-slider-button"
                                                        data-post='<?php echo $postData; ?>'
                                                        type="button" title="<?php echo __('Add to Cart') ?>">
                                                    <span><?php echo __('Add to Cart') ?></span>
                                                </button>
                                            <?php endif; ?>
                                        <?php else: ?>
                                            <?php if ($product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php echo __('In stock') ?></span>
                                                </div>
                                            <?php else: ?>
                                                <div class="stock unavailable">
                                                    <span><?php echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                </div> */ ?>
                            </div>
                        </div>
                    <?php echo ($iterator == count($collection) + 1) ? '</div>' : '' ?>
                <?php endforeach; ?>
            </div>
        </div>
        <?php //echo $block->getPagerHtml() ?>
        
    </div>

    <script>
        require([
                'jquery',
                'mageplaza/core/owl.carousel'
            ], function ($) {
                jQuery("#featured-list").owlCarousel({
   responsive:{
                        0:{
                            items:2
                        },
                        480:{
                            items:2
                        },
                        768:{
                            items:3
                        },
                        992:{
                            items:1
                        },
                        1200:{
                            items:5,
                            
                        

                        }
                    },
                    autoWidth:0,
                    autoHeight:1,
                 
                    autoplay:false,
                    loop:true,
                    nav : true,
                    dots: false,
                    autoplaySpeed : 5000,
                    navSpeed : 500,
                    dotsSpeed : 500,
                    autoplayHoverPause: true,
                    margin:30,
                    lazyLoad:true
                });   
            }); 
                
    </script>

<?php endif; ?>



