<?php 
/**
 * InfoBeans Sales Shipment Comment Extension
 *
 * @category   Infobeans
 * @package    Infobeans_OSComments
 * @version    2.0.0
 *
 * Release with version 2.0.0
 *
 * @author     InfoBeans Technologies Limited http://www.infobeans.com/
 * @copyright  Copyright (c) 2017 InfoBeans Technologies Limited
 */    
?>
<div class="checkout-shipping-method">
    <div class="step-title"><?php echo __($this->helper('Infobeans\OSComments\Helper\Data')->getShippingLabel());?></div>
    <div>&nbsp;</div>
    <div id="checkout-step-shipping_method" class="step-content">
        <textarea name="delivery_comment" id="delivery_comment"></textarea>
    </div>
</div>