
<?php $rma = $block->getRmaDetail();
    $id = $rma->getRmaId();
    $order = $block->getOrder($rma->getOrderId());
    $helper = $this->helper("Webkul\Rmasystem\Helper\Data");

?>
<form method="post" action="<?= $this->getUpdateUrl(); ?>" id="edit_form" enctype="multipart/form-data" data-mage-init='{"validation":{}}'>
    <!-- <fieldset class="fieldset admin__fieldset fieldset-wide"> -->
    <input type="hidden" value="<?= $block->getFormKey() ?>" name="form_key"/>
    <input type="hidden" value="<?= $id ?>" name="rma_id"/>
    <input type="hidden" value="<?= $order->getId() ?>" name="order_id"/>
        <section class="admin__page-section order-view-account-information">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-content">
            <table class="admin__table-secondary order-information-table">
                <tbody>
                    <tr>
                        <th><?= __("Order Id"); ?></th>
                        <td><a href="<?= $this->getUrl('sales/order/view/', ['_secure' => $this->getRequest()->isSecure()]).'order_id/'.$rma->getOrderId(); ?>">#<?= $rma->getIncrementId();?></a></td>
                    </tr>
                    <?php if (!$rma->getResolutionType()==3): ?>
                    <tr>
                        <th><?= __("Package Condition"); ?></th>
                        <td>
                            <?php if ($rma->getPackageCondition() == 0) {
                                echo "<p>".__("Open")."</p>";
                            } else {
                                echo "<p>".__("Packed")."</p>";
                            }?>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <tr>
                        <th><?= __("Created On"); ?></th>
                        <td><p><?= date("Y-m-d g:i:s a", $block->getTimestamp($rma->getCreatedAt())); ?></p></td>
                    </tr>
                    <tr>
                        <th><?= __("Customer Consignment Number"); ?></th>
                        <td><?= $rma->getCustomerConsignmentNo(); ?></td>
                    </tr>
                    <tr>
                        <th><?= __("Admin Consignment Number"); ?></th>
                        <td><?= $rma->getAdminConsignmentNo(); ?></td>
                    </tr>
                    <tr>
                        <th><h3><?= __("Additional Image(s)"); ?></h3></th>
                        <td>
                            <div id="wk_rma_add_images_container">
                        <?php
                            $images = $block->getImages();
                        foreach ($images as $filename) {
                            $getfilename = explode("/", $filename);
                            $justfname = $block->getBaseUrl()."/".end($getfilename);
                            echo "<img class='wk_rma_add_images' alt='image' src='".$justfname."'/>";
                        }   ?>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
            </div>
        </div>
            <div class="admin__page-section-item order-account-information">
            <div class="admin__page-section-content">
                <table class="admin__table-secondary order-account-information-table">
                <tbody>
                    <tr>
                        <th><?= __("RMA Status"); ?></th>
                        <td>
                            <span>
                                    <?= "<strong class='wk_rma_status_pending'>".$helper->getRmaStatusTitle($rma->getStatus())."</strong>";?>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <th><?= __("Product Delivery Status"); ?></th>
                        <td>
                            <span>
                                    <?= "<strong class='wk_rma_status_pending'>".$helper->getRmaOrderStatusTitle($rma->getCustomerDeliveryStatus())."</strong>";?>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <th><?= __("Resolution Type"); ?></th>
                        <td>
                            <?php if ($rma->getResolutionType() == 0) {
                                echo "<p>".__("Refund")."</p>";
                            } elseif ($rma->getResolutionType() == 1) {
                                echo "<p>".__("Exchange")."</p>";
                            } else {
                                echo "<p>".__("Cancel Item")."</p>";
                            }?>
                        </td>
                    </tr>
                    <tr>
                        <th><?= __("Additional Information"); ?></th>
                        <td><p><?= nl2br(strip_tags($rma->getAdditionalInfo())); ?></p></td>
                    </tr>
                    <?php if ($rma->getResolutionType() == 1) {?>
                    <tr>
                        <th><?= __("Admin Consignment Number"); ?></th>
                        <td><p><?= $rma->getAdminConsignmentNo(); ?></p></td>
                    </tr>
                    <?php } ?>
                    <?= $this->getChildHtml('rma.allrma.customfield'); ?>
                </tbody>
            </table>
            </div>
        </div>
        </section>
            <div id="view-rma-component" data-bind="scope:'view-rma-component'" class="field">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                    <script type="text/x-magento-init">
                    {
                            "#view-rma-component": {
                                    "Magento_Ui/js/core/app":  <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
                            }
                    }
                    </script>
                <section class="admin__page-section">
                <div class="admin__page-section-title" style="clear:both">
                    <span class="title"><?= __("Item(s) Requested for RMA"); ?></span>
                </div>
                <div class="admin__table-wrapper">
                <table class="data-table">
                    <thead>
                        <tr>
                            <th><?= __("Product Name"); ?></th>
                            <th><?= __("SKU"); ?></th>
                            <th class="a-right"><?= __("Return Qty"); ?></th>
                            <th class="a-right"><?= __("Reason"); ?></th>
                            <th class="a-right"><?= __("Product Price"); ?></th>
    
                        </tr>
                    </thead>
                    <?php   $orderItems = $block->getItemCollection($id);
                                    $download_count=count($orderItems);
                                    $download=0;
                                    $itemIds = [];
                    foreach ($orderItems as $item) {
                        $itemIds[] = $item->getItemId();
                        $mageItem = $block->getSalesOrderItemDetail($item->getItemId());
                        $product = $block->getProductDetail($mageItem->getProductId());
                        $reason = $block->getReason($item->getReasonId())->getReason();
                        if (!$reason) {
                            $reason = $item->getRmaReason();
                        }
                        if ($product->getTypeId()=='downloadable' || $product->getTypeId()=='virtual') {
                            $download++;
                        }
                        ?>
                        <tbody>
                            <tr class="border">
                                <td><h3 class="product-name"><?= $mageItem->getName(); ?></h3></td>
                                <td><?= $mageItem->getSku(); ?></td>
                                <td class="a-right"><?= $item->getQty(); ?></td>
                                <td class="a-right"><?= $reason; ?></td>
                                    <td class="a-right"><?= $order->formatPrice($mageItem->getPrice()); ?></td>
                                </tr>
                                        </tbody>
                    <?php   } ?>
                            </table>
                        </div>
                </section>
            <div id="wk_rma_conversation_container">
                    <div class="conversation-block" style="float:left;width:40%;">
                        <div class="admin__page-section-item-title">
                <span class="title"><?= __('RMA History & Conversation') ?></span>
            </div>
        <?php   $collection = $this->getConvsersationCollection($rma->getRmaId());
        if ($rma->getCustomerId() > 0) {
            $customer = $block->getCustomerDetail($rma->getCustomerId());
            $customerName = $customer->getFirstname()." ".$customer->getLastname();
        } else {
            $customerName = $rma->getGuestEmail()." (".__("Guest").")";
        }
        foreach ($collection as $eachconver) {  ?>
                    <div class="wk_rma_onereply">
                        <span class="wk_rma_onereply_head <?php if ($eachconver->getSender() == 'customer' || $eachconver->getSender() == 'guest') {
                            echo "wk_rma_onereply_customer";
                                                          }?>">
                            <span class="wk_rma_onereply_head_left"><?= date("Y-m-d g:i:s a", $block->getTimestamp($eachconver->getCreatedAt())); ?></span>
                                        <span class="wk_rma_onereply_head_right">
                                    <?php if ($eachconver->getSender() == 'customer' || $eachconver->getSender() == 'guest') {
                                                echo __($customerName);
                                    } else {
                                        echo __("Admin");
                                    } ?></span>
                        </span>
                        <?php if ($eachconver->getSender() == 'default'): ?>
                                <div class="wk_rma_onereply_cntnt"><?= $eachconver->getMessage(); ?></div>
                        <?php else: ?>
                                <p class="wk_rma_onereply_cntnt">
                                    <span><?= nl2br(strip_tags($eachconver->getMessage())); ?></span></br>
                                    <?php if ($eachconver->getAttachment() != '') { ?>
                                        <a target="_blank" href="<?= $helper->getConversationUrl($id). $eachconver->getAttachment()?>"><?= $eachconver->getAttachment() ?></a>
                                    <?php } ?>
                                </p>
                        <?php endif; ?>
                    </div>
        <?php   }   ?>
        </div>
    </div>
</form>
<script>
require([
        "jquery",
        "mage/mage",
        'mage/calendar'
    ], function($){
            'use strict';
            window.print();
            $('.page-main-actions').remove();
        });
</script>

