<div id='toTop'>Top</div>
<script type="text/javascript">
require([ 
	'jquery', 
	'jquery/ui'], 
	function($){ 
		$(document).ready(function($) {
				$(window).scroll(function() {
				    if ($(this).scrollTop() > 100) {
				        $('#toTop').fadeIn();
				    } else {
				        $('#toTop').fadeOut();
				    }
				});

				$("#toTop").click(function () {
				   $("html, body").animate({scrollTop: 0}, 1000);
				});
		}); 
});
</script>