<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();

$om = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $om->get('Magento\Customer\Model\SessionFactory')->create();
$fname = $customerSession->getCustomer()->getFirstname();
$lname = $customerSession->getCustomer()->getLastname();

/*echo "<pre>";
print_r($customerSession->getData());
exit;*/
?>
<li class="greet welcome">
        <?php if ($customerSession->isLoggedIn()) { ?>
        <span class="logged-in"><?php echo $fname." ".$lname; ?></span>
    <?php } else{ ?>
        <span class="not-logged-in"><?php echo $block->escapeHtml($welcomeMessage) ?></span>
    <?php } ?>
<?php /*if ($block->getShowPart() == 'welcome') : ?>
    <li class="greet welcome" data-bind="scope: 'customer'">
        <?php if ($customerSession->isLoggedIn()) { ?>
        <span class="logged-in"><?php echo $fname." ".$lname; ?></span>
    <?php } else{ ?>
        <span class="not-logged-in"><?php echo $block->escapeHtml($welcomeMessage) ?></span>
    <?php } ?>

        <!-- ko if: customer().fullname  -->
        <?php /*<span class="logged-in"
              data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().fullname)">
        </span> */ ?>
        <!-- /ko -->
        <!-- ko ifnot: customer().fullname  -->
        <?php /* <span class="not-logged-in"
              data-bind='html:"<?= $block->escapeHtml($welcomeMessage) ?>"'></span> */ ?>
        <?php /*<?= $block->getBlockHtml('header.additional') ?> */?>
        <!-- /ko -->
    </li>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>
<?php /*elseif ($block->getShowPart() == 'other') :?>
    <?= $block->getChildHtml() ?>
<?php endif*/ ?>
