<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MagentoChatSystem
 * @author    Webkul
 * @copyright Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/**
 * Template for block \Webkul\MagentoChatSystem\Block\Adminhtml\Edit\Tab\View
 */

/** @var $block \Webkul\MagentoChatSystem\Block\Adminhtml\Edit\Tab\View */
?>
<?= $block->getChildHtml();
