<?php

/**
* Magedelight
* Copyright (C) 2017 Magedelight <info@magedelight.com>
*
* @category Magedelight
* @package Magedelight_MembershipSubscription
* @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
* @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
* @author Magedelight <info@magedelight.com>
 */
?>

<?php
$expiryInfo = $block->getExpiry();
if (count($expiryInfo)>0) { ?>

    <p>Dear Customer,</p>
    <p>Your <?php echo $expiryInfo['plan_name']; ?> Membership will expire on  <?php echo $expiryInfo['plan_expiry_date']; ?>.</p>
    <p>Please renew your Membership click <a href="<?php echo $expiryInfo['renew_url']; ?>"> <b><i>here</i></b>. </a></p>
    
<?php } ?>
